#!/usr/bin/env python3
"""Generate a Caddyfile from routes.json.

routes.json is a list of routes:

    [
        {"path": "/flowlet/api/*", "port": 8000},
        {"path": "/flowlet/*",     "port": 3000}
    ]

Each route forwards requests matching `path` to 127.0.0.1:<port>.

Optional per-route keys:
    "strip": true   — strip the matched prefix before forwarding
                      (Caddy `handle_path`). Default false: the backend
                      receives the full original path (Caddy `handle`),
                      which is what apps mounted under a prefix expect.

Routes are emitted longest-path-first so more specific paths win
(/flowlet/api/* is matched before /flowlet/*). A 404 fallback is added
unless a route already covers everything (path "/*" or "/").

Usage:
    generate-caddyfile.py [routes.json] [-o Caddyfile] [--listen 8080]
"""

import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def fail(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def load_routes(config_path):
    try:
        routes = json.loads(Path(config_path).read_text())
    except FileNotFoundError:
        fail(f"config not found: {config_path}")
    except json.JSONDecodeError as e:
        fail(f"invalid JSON in {config_path}: {e}")

    if not isinstance(routes, list) or not routes:
        fail("config must be a non-empty JSON array of routes")

    seen = set()
    for i, route in enumerate(routes):
        where = f"route #{i + 1}"
        if not isinstance(route, dict):
            fail(f"{where}: must be an object")

        unknown = set(route) - {"path", "port", "strip"}
        if unknown:
            fail(f"{where}: unknown keys: {', '.join(sorted(unknown))}")

        path = route.get("path")
        if not isinstance(path, str) or not path.startswith("/"):
            fail(f"{where}: \"path\" must be a string starting with '/'")
        if path in seen:
            fail(f"{where}: duplicate path {path!r}")
        seen.add(path)

        port = route.get("port")
        if not isinstance(port, int) or not 1 <= port <= 65535:
            fail(f"{where} ({path}): \"port\" must be an integer in 1-65535")

        if not isinstance(route.get("strip", False), bool):
            fail(f"{where} ({path}): \"strip\" must be true or false")

    return routes


def render(routes, listen_port):
    routes = sorted(routes, key=lambda r: len(r["path"]), reverse=True)
    has_catch_all = any(r["path"] in ("/", "/*") for r in routes)

    lines = [
        "# Generated by scripts/generate-caddyfile.py from routes.json — do not edit by hand.",
        "# Regenerate + deploy with: scripts/apply.sh",
        "{",
        "\tauto_https off",
        "}",
        "",
        f":{listen_port} {{",
    ]
    for route in routes:
        directive = "handle_path" if route.get("strip") else "handle"
        lines += [
            f"\t{directive} {route['path']} {{",
            f"\t\treverse_proxy 127.0.0.1:{route['port']}",
            "\t}",
        ]
    if not has_catch_all:
        lines += [
            "\thandle {",
            '\t\trespond "no route configured for this path" 404',
            "\t}",
        ]
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("config", nargs="?", default=str(ROOT / "routes.json"),
                        help="path to routes.json (default: repo root)")
    parser.add_argument("-o", "--output", default="-",
                        help="output file (default: stdout)")
    parser.add_argument("--listen", type=int,
                        default=int(os.environ.get("PROXY_PORT", "8080")),
                        help="port Caddy listens on (default: $PROXY_PORT or 8080)")
    args = parser.parse_args()

    caddyfile = render(load_routes(args.config), args.listen)
    if args.output == "-":
        sys.stdout.write(caddyfile)
    else:
        Path(args.output).write_text(caddyfile)
        print(f"wrote {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
